version: 0.0
os: linux

files:
  - source: /
    destination: /home/centos/webapp

hooks:
  AfterInstall:
    - location: /after-install.sh
      timeout: 180
      runas: centos
  ApplicationStart:
    - location: npm-start.sh
      timeout: 180
      runas: centos