version: 0.0
os: linux

files:
  - source: /
    destination: /home/centos/www

hooks:
  BeforeInstall:
    - location: before-install.sh
      timeout: 300
      runas: root
  AfterInstall:
    - location: after-install.sh
      timeout: 300
      runas: root
  ApplicationStart:
    - location: application-start.sh
      timeout: 300
      runas: root