version: 1.1
jobs:
  build:
    docker:
      - image: circleci/node:8
    steps:
      - checkout

      - run:
          name: Install packages
          command: |
            sudo apt-get update && sudo apt-get install wget zip unzip python-dev  \
              build-essential libssl-dev libffi-dev \
              libxml2-dev libxslt1-dev zlib1g-dev python2.7 python-pip -y

      - run:
          name: Install awscli
          command: sudo pip install awscli

      - run:
          name: Build Artifact
          command: |
            cd webapp
            pwd
            ls -al
            npm install
            ls -al
            cd ../
            pwd
            ls -al
      - run:
          name: Zip Artifact
          command: |
            echo "Hello the current build number is ${CIRCLE_BUILD_NUM}"
            pwd
            mkdir -p codedeploy_artifact
            cp infrastructure/aws/codedeploy/*.sh .
            zip -r csye6225-web-app-${CIRCLE_BUILD_NUM}.zip webapp/ *.sh *.yml -x webapp/node_modules/\*
            mv csye6225-web-app-${CIRCLE_BUILD_NUM}.zip codedeploy_artifact/
            cd codedeploy_artifact
            ls -al
            pwd
            cd ..
            pwd
            ls -al
      - run:
          name: Upload Artifact to S3
          command: |
            aws s3 sync codedeploy_artifact s3://${CODE_DEPLOY_S3}
      - run:
          name: Make CodeDeploy API call
          command: |
            echo "Hello CodeDeploy"
      - run:
          name: Create Deployment
          command: |
            echo "Hello CodeDeploy"
            aws deploy create-deployment-group\
              --ec2-tag-filters Key=csye6225,Value=webapp\
              --auto-rollback-configuration enabled=true,events=DEPLOYMENT_FAILURE\
              --application-name csye6225-webapp\
              --deployment-config-name CodeDeployDefault.OneAtATime\
              --deployment-group-name csye6225-webapp-deployment\
              --s3-location bucket=${CODE_DEPLOY_S3},bundleType=zip,key=csye6225-web-app-${CIRCLE_BUILD_NUM}.zip