---
Description: >-
  Application stack.
AWSTemplateFormatVersion: 2010-09-09

Parameters:
  image:
    Type: String
  ExportStackName:
    Type: String
  S3Attachments:
    Type: String
  SNSARN:
    Type: String
  DBPassword:
    Type: String
  DBUsername:
    Type: String
  DomainName:
    Type: String

Resources:
  DBSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupName: "Database Internet Group"
      GroupDescription: "SSH traffic in, all traffic out."
      VpcId:
       Fn::ImportValue: !Sub '${ExportStackName}-VPC'
      SecurityGroupIngress:
      - IpProtocol: tcp
        FromPort: '3306'
        ToPort: '3306'
        CidrIp: 0.0.0.0/0
      SecurityGroupEgress:
      - IpProtocol: -1
        CidrIp: 0.0.0.0/0
  # Ec2Instance:
  #   Type: AWS::EC2::Instance
  #   Properties:
  #     ImageId: !Ref image
  #     InstanceType: t2.micro
  #     Volumes:
  #       - Device: "/dev/sdh"
  #         VolumeId: !Ref Volume
  #     IamInstanceProfile: "EC2profile"
  #     KeyName: csye6225
  #     SubnetId:
  #         Fn::ImportValue: !Sub '${ExportStackName}-SubnetB'
  #     AvailabilityZone: us-east-1b
  #     SecurityGroupIds:
  #       - Fn::ImportValue: !Sub '${ExportStackName}-SecurityGroup'
  #     Tags:
  #       - Key: csye6225
  #         Value: webapp
  #     UserData:
  #       Fn::Base64:
  #         Fn::Join:
  #         - "\n"
  #         - - "#!/bin/bash"
  #           - yum install python-dev build-essential libssl-dev libffi-dev libxml2-dev libxslt1-dev zlib1g-dev python2.7 python-pip -y
  #           - pip install awscli
  #           - cd /home/centos
  #           - cat <<EOT >> env
  #           - AWS_ACCESS_KEY=""
  #           - AWS_SECRET_ACCESS_KEY=""
  #           - Fn::Join:
  #             - ""
  #             - - AWS_BUCKET=
  #               - !Ref S3Attachments
  #           - Fn::Join:
  #             - ""
  #             - - TOPIC_NOTIFY_ARN=
  #               - !Ref SNSARN
  #           - WEB_PORT=80
  #           - Fn::Join:
  #             - ''
  #             - - DB_HOST=
  #               - Fn::GetAtt:
  #                 - MyDB
  #                 - Endpoint.Address
  #           - DB_NAME="csye6225"
  #           - Fn::Join:
  #             - ""
  #             - - DB_USERNAME=
  #               - !Ref DBUsername
  #           - Fn::Join:
  #             - ""
  #             - - DB_PASSWORD=
  #               - !Ref DBPassword
  #           - EOT

  EC2AutoScalingGroup:
    Type: AWS::AutoScaling::AutoScalingGroup
    Properties:
      # AutoScalingGroupName: String
      Cooldown: 60
      MaxSize: 10
      MinSize: 3
      DesiredCapacity: 3
      LaunchConfigurationName: asg_launch_config
  EC2ConfigurationGroup:
    Type: AWS::AutoScaling::LaunchConfiguration
    Properties:
      ImageId: !Ref image
      InstanceType: t2.micro
      KeyName: csye6225
      AssociatePublicIpAddress: True
      LaunchConfigurationName: asg_launch_config
      SecurityGroups:
        - Fn::ImportValue: !Sub '${ExportStackName}-SecurityGroup'
      UserData:
        Fn::Base64:
          Fn::Join:
          - "\n"
          - - "#!/bin/bash"
            - yum install python-dev build-essential libssl-dev libffi-dev libxml2-dev libxslt1-dev zlib1g-dev python2.7 python-pip -y
            - pip install awscli
            - cd /home/centos
            - cat <<EOT >> env
            - AWS_ACCESS_KEY=""
            - AWS_SECRET_ACCESS_KEY=""
            - Fn::Join:
              - ""
              - - AWS_BUCKET=
                - !Ref S3Attachments
            - Fn::Join:
              - ""
              - - TOPIC_NOTIFY_ARN=
                - !Ref SNSARN
            - WEB_PORT=80
            - Fn::Join:
              - ''
              - - DB_HOST=
                - Fn::GetAtt:
                  - MyDB
                  - Endpoint.Address
            - DB_NAME="csye6225"
            - Fn::Join:
              - ""
              - - DB_USERNAME=
                - !Ref DBUsername
            - Fn::Join:
              - ""
              - - DB_PASSWORD=
                - !Ref DBPassword
            - EOT
  Volume:
    Type: AWS::EC2::Volume
    Properties:
      Size: 20
      VolumeType: gp2
      AvailabilityZone: us-east-1b
  MyDB:
    Type: AWS::RDS::DBInstance
    Properties:
      DBInstanceClass: db.t2.medium
      Engine: MySQL
      DBInstanceIdentifier: csye6225-spring2019
      MultiAZ: false
      MasterUsername: !Ref DBUsername
      MasterUserPassword: !Ref DBPassword
      DBSubnetGroupName: !Ref myDBSubnetGroup
      PubliclyAccessible: true
      DBName: "csye6225"
      AllocatedStorage: "100"
      VPCSecurityGroups:
        - !Ref DBSecurityGroup
  myDBSubnetGroup:
    Type: "AWS::RDS::DBSubnetGroup"
    Properties:
      DBSubnetGroupDescription: "DBSubnets"
      SubnetIds:
        - Fn::ImportValue: !Sub '${ExportStackName}-SubnetA'
        - Fn::ImportValue: !Sub '${ExportStackName}-SubnetB'
        - Fn::ImportValue: !Sub '${ExportStackName}-SubnetC'
  DyDB:
    Type: AWS::DynamoDB::Table
    Properties:
      AttributeDefinitions:
        -
          AttributeName: "id"
          AttributeType: "S"
      KeySchema:
        -
          AttributeName: "id"
          KeyType: "HASH"
      ProvisionedThroughput:
            ReadCapacityUnits: "5"
            WriteCapacityUnits: "5"
      TableName: csye6225
      Tags:
      - Key: Name
        Value: csye6225
  SSL:
    Type: AWS::CertificateManager::Certificate
    Properties:
      DomainName: !Ref DomainName